/**
 * App's api endpoints
 */
export default {
  getPermissions: 'vbc-admin/api/permissions',
  register: 'vbc-patient/api/register',
  resendOtp: 'vbc-patient/api/resend-otp',
  addDevice: 'vbc-admin/user/add-device',
  logout: 'vbc-admin/user/logout',
  forgotPasswordNew: 'vbc-admin/user/forgot-password',
  contactSupport: 'vbc-admin/user/contact-support',
  verifyOTP: 'vbc-patient/api/register/verify',
  resetPassword: 'vbc-patient/api/reset-password',
  changePassword: 'vbc-admin/user/change-password',
  verifyContactDetailsApplicant: 'vbc-patient/applicant/verify-contact-details',
  verifyContactDetailsPatient: 'vbc-patient/api/verify-contact-details',
  getOtpPatient: 'vbc-patient/api/send-verification-otp',
  getOtpApplicant: 'vbc-patient/applicant/send-verification-otp',
  fetchHospitals: 'vbc-patient/api/hospitals',
  fetchDrugs: 'vbc-patient/api/drugs',
  fetchDoctors: 'vbc-patient/api/doctors',
  fetchCities: 'vbc-patient/api/cities',
  registrationCompleteYourProfile: 'vbc-patient/api/complete-your-profile',
  editRegistrationCompleteYourProfile: 'vbc-patient/api/profile/update',
  editApplicantRegistrationCompleteYourProfile:
    'vbc-patient/applicant/profile/update',
  getRegistrationCompleteYourProfile: 'vbc-patient/api/your-details',
  getApplicantProfileDetails: 'vbc-patient/applicant/profile/details',
  vbcProgramEnrollment: 'vbc-patient/api/enroll-for-vbc',
  getVbcProgramEnrollment: 'vbc-patient/api/get-enrollment-data',
  vbcGetLoanAmount: 'vbc-patient/api/get-amount',
  fetchFinancialInformation: 'vbc-patient/api/get-financial-information',
  editFinancialInformation: 'vbc-patient/api/update-financial-information',
  userInfo: 'vbc-admin/user/get-user',
  getMasterData: 'vbc-admin/api/master-data',
  getDocumentTypes: 'vbc-document/document/get-data',
  getUploadedDocuments: 'vbc-document/document/list',
  uploadDocument: 'vbc-document/document/upload-document-for-applicant',
  uploadDocumentPatient: 'vbc-document/document/upload-document-for-patient',
  deleteDocument: 'vbc-document/document/delete',
  downloadDocument: 'vbc-document/document/get',
  fetchApplicantOverviewData: 'vbc-patient/applicant/loan-application/overview',
  fetchApplicantsData: 'vbc-patient/api/applicants',
  fetchAlerts: 'vbc-notification/api/notifications',
  readAlert: 'vbc-notification/api/notifications/mark-read',
  submitToMangoExecutive: 'vbc-patient/api/submit-to-mango-executive',
  fetchApplicantLoanApplicationDetails:
    'vbc-patient/applicant/loan-application/details',
  fetchApplicantFinancialInformationData:
    'vbc-patient/applicant/financial-data/details',
  submitApplicantCompleteApplicationStep1:
    'vbc-patient/applicant/loan-application/step-one',
  submitApplicantCompleteApplicationStep2:
    'vbc-patient/applicant/loan-application/step-two',
  submitApplicantCompleteApplicationStep3:
    'vbc-patient/applicant/loan-application/step-three',
  submitApplicantCompleteApplicationStep4:
    'vbc-patient/applicant/loan-application/step-four',
  getRequiredDocuments: 'vbc-document/document/required-documents',
  storeVbcProgramStep1: 'vbc-patient/api/enroll-for-vbc/step-one',
  storeVbcProgramStep2: 'vbc-patient/api/enroll-for-vbc/step-two',
  storeVbcProgramStep3: 'vbc-patient/api/enroll-for-vbc/step-three',
  storeVbcProgramStep4: 'vbc-patient/api/enroll-for-vbc/step-four',
  addApplicant: 'vbc-patient/api/applicant/add',
  deleteApplicant: 'vbc-patient/api/applicant/remove/',
  getTokenForResetPassword: 'vbc-admin/api/user-info',
  getVersionInfo: 'vbc-admin/api/check-version-support',
  getVbcSchedule: 'vbc-patient/api/schedule/',
  getDrugSchedule: 'vbc-patient/api/drug-schedule',
  acknowledgeFirstGrant: 'vbc-patient/api/acknowledge-first-grant',
  getReports: 'vbc-patient-data/api/',
  getReportsSyncStatus: 'vbc-patient-data/api/check-data-synchronization',
  getDrugScheduleOverview: 'vbc-patient/api/drug-schedule-overview',
  reapplyVbcProgramApiCall: 'vbc-patient/api/reapply-application',
  cancelVbcProgramApiCall: 'vbc-patient/api/cancel-application',
  GET_CSRF_TOKEN: 'csrf',
};
