/**
 * Stylesheet definition for Help screen component
 */
import {StyleSheet} from 'react-native';
import {Theme} from 'constants';
import {dynamicSize, fontFamily, fontSizes} from 'utils';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  needMore: {
    fontSize: fontSizes.medium,
    fontFamily: fontFamily.medium,
    color: Theme.darkTextColor,
    margin: dynamicSize(6),
  },
  innerItem: {
    marginVertical: dynamicSize(10),
  },
  cantFind: {
    fontSize: fontSizes.small,
    fontFamily: fontFamily.regular,
    color: Theme.lightTextColor,
    margin: dynamicSize(6),
  },
  SectionStyle: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderWidth: 0.5,
    borderColor: '#000',
    height: 40,
    borderRadius: 5,
    margin: 10,
  },
  ImageStyle: {
    padding: 10,
    margin: 5,
    height: 25,
    width: 25,
    resizeMode: 'stretch',
    alignItems: 'center',
  },
  callUs: {
    fontSize: fontSizes.small,
    fontFamily: fontFamily.regular,
    color: Theme.lightTextColor,
    margin: dynamicSize(6),
  },
  visitUs: {
    fontSize: fontSizes.small,
    fontFamily: fontFamily.regular,
    color: Theme.lightTextColor,
    margin: dynamicSize(6),
  },
  separator: {
    width: '100%',
    height: 1,
    backgroundColor: Theme.lightBorderColor,
    marginTop: 30,
    marginBottom: 20,
  },
  url: {
    fontSize: fontSizes.small,
    fontFamily: fontFamily.regular,
    color: Theme.primary,
    margin: dynamicSize(6),
  },
  scrollContentContainer: {
    backgroundColor: Theme.snow,
    paddingHorizontal: dynamicSize(20),
    paddingVertical: dynamicSize(20),
  },
  // containerContainer: {
  //   height: dynamicSize(1020),
  //   marginVertical: dynamicSize(10),
  // },
  scrollContainer: {
    flex: 1,
    backgroundColor: Theme.snow,
  },
  horizontalTimelineContainer: {
    marginVertical: dynamicSize(10),
    marginBottom: dynamicSize(40),
  },
  containerContainer: {
    // height: dynamicSize(930),
    marginVertical: dynamicSize(10),
  },
  containerContainerSmall: {
    // height: dynamicSize(850),
    marginBottom: dynamicSize(10),
  },
  containerHeadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: dynamicSize(20),
  },
  containerHeading: {
    fontFamily: fontFamily.regular,
    fontSize: fontSizes.medium,
    color: Theme.lightTextColor,
  },
  textInputContainer: {
    marginTop: dynamicSize(20),
    width: dynamicSize(285),
    fontFamily: fontFamily.regular,
    fontSize: fontSizes.medium,
  },
  textInputContainerMessage: {
    marginTop: dynamicSize(20),
    width: dynamicSize(285),
    fontFamily: fontFamily.regular,
    fontSize: fontSizes.medium,
    height: dynamicSize(150),
    textAlignVertical: 'top',
    paddingVertical: dynamicSize(5),
  },
  note: {
    marginTop: dynamicSize(20),
    fontFamily: fontFamily.light,
    fontSize: fontSizes.small,
    color: Theme.lightTextColor,
  },
  buttonContainer: {
    height: dynamicSize(45),
    width: dynamicSize(190),
    alignItems: 'center',
    marginTop: dynamicSize(50),
    borderRadius: 5,
    backgroundColor: Theme.primary,
    flexDirection: 'row',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  saveButton: {
    height: dynamicSize(35),
    width: dynamicSize(100),
    alignItems: 'center',
    borderRadius: 5,
    backgroundColor: Theme.primary,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  cancelButton: {
    height: dynamicSize(35),
    width: dynamicSize(100),
    alignItems: 'center',
    borderRadius: 5,
    backgroundColor: Theme.darkPrimary,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  buttonText: {
    fontFamily: fontFamily.medium,
    fontSize: fontSizes.medium,
    color: Theme.snow,
  },
  expandableItemContainer: {
    marginVertical: dynamicSize(15),
  },
  expandableItemChildContainer: {
    backgroundColor: Theme.lightBlueGreen,
    borderWidth: 1,
    borderColor: Theme.blueGreen,
    borderTopRightRadius: 0,
    borderTopLeftRadius: 0,
    paddingHorizontal: dynamicSize(10),
    borderRadius: 5,
    paddingVertical: dynamicSize(20),
  },
  innerExpandableItemChildContainer: {
    backgroundColor: Theme.lightBlueGreen,
    borderWidth: 1,
    borderColor: Theme.blueGreen,
    borderTopRightRadius: 0,
    borderTopLeftRadius: 0,
    paddingHorizontal: dynamicSize(10),
    borderRadius: 5,
    paddingVertical: dynamicSize(10),
  },
  detailsContainer: {
    marginVertical: dynamicSize(12),
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  details: {
    fontFamily: fontFamily.regular,
    fontSize: fontSizes.small,
    color: Theme.lightTextColor,
  },
  expandableContainer: {
    marginVertical: dynamicSize(30),
  },
  expandableChildrenButtonContainer: {
    height: dynamicSize(35),
    width: dynamicSize(80),
    alignItems: 'center',
    marginVertical: dynamicSize(25),
    borderRadius: 5,
    backgroundColor: Theme.primary,
    flexDirection: 'row',
    justifyContent: 'center',
    alignSelf: 'flex-end',
  },
  expandableChildrenButton: {
    fontFamily: fontFamily.regular,
    fontSize: fontSizes.small,
    color: Theme.snow,
  },
  saveAndProceedButtonContainer: {
    height: dynamicSize(45),
    width: dynamicSize(210),
    alignItems: 'center',
    marginTop: dynamicSize(35),
    borderRadius: 5,
    backgroundColor: Theme.primary,
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: dynamicSize(10),
  },
  headingIcon: {
    marginRight: 10,
  },
  applicantContainer: {
    marginVertical: dynamicSize(30),
    width: '100%',
  },
  accountDetailsContainerEditButton: {
    backgroundColor: Theme.primary,
    height: dynamicSize(30),
    width: 80,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    position: 'absolute',
    right: 5,
  },
  accountDetailsContainerHeading: {
    fontFamily: fontFamily.medium,
    fontSize: fontSizes.medium,
    color: Theme.lightTextColor,
  },
  accountDetailsContainerEditButtonText: {
    fontFamily: fontFamily.regular,
    fontSize: fontSizes.xsmall,
    color: Theme.snow,
  },
  buttonIconContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    height: 24,
    width: 24,
    borderRadius: 14,
    backgroundColor: Theme.snow,
    position: 'absolute',
    right: 10,
  },
  buttonIcon: {
    fontSize: fontSizes.small,
    color: Theme.currentStatusColor,
  },
  apiErrorText: {
    fontFamily: fontFamily.regular,
    fontSize: fontSizes.small,
    color: Theme.error,
    textAlign: 'center',

    fontStyle: 'italic',
  },
  seperator: {
    marginBottom: dynamicSize(15),
  },
  answerStyles: {
    fontFamily: fontFamily.regular,
    fontSize: fontSizes.small,
    color: Theme.lightTextColor,
  },
});
